Fix mixed-precision handling and add jaxtyping annotations
In particular it seems that einsum doesn't like operands with different
precisions:

>   File "./bergson/bergson/hessians/sharded_computation.py", line 210, in _sharded_matmul
>     result_nsb += torch.einsum(
>   File "./.venv/lib/python3.10/site-packages/torch/functional.py", line 422, in einsum
>     return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
> RuntimeError: expected scalar type Float but found BFloat16

So we add .float() where needed to turn operands into float32.

For now, the more precise typing annotations are for documentation purpose, but
we should probably enable jaxtyping runtime type-checking at least in tests to
check them: https://docs.kidger.site/jaxtyping/api/runtime-type-checking/
(I don't think this will catch missing .float() when calling einsum unfortunately).